package com.Utils;
public enum CustomTimeZone {
    AfricaAbidjan("格林威治", 0, "Africa/Abidjan"),
    Africa_Accra("加纳时间", 0, "Africa/Accra"),
    Africa_Addis_Ababa("东非时间", 3, "Africa/Addis_Ababa"),
    Africa_Algiers("中欧时间", 1, "Africa/Algiers"),
    Africa_Asmara("东非时间", 3, "Africa/Asmara"),
    Africa_Asmera("东非时间", 3, "Africa/Asmera"),
    Africa_Bamako("格林威治时间", 0, "Africa/Bamako"),
    Africa_Bangui("西非时间", 1, "Africa/Bangui"),
    Africa_Banjul("格林威治时间", 0, "Africa/Banjul"),
    Africa_Bissau("格林威治时间", 0, "Africa/Bissau"),
    Africa_Blantyre("中非时间", 2, "Africa/Blantyre"),
    Africa_Brazzaville("西非时间", 1, "Africa/Brazzaville"),
    Africa_Bujumbura("中非时间", 2, "Africa/Bujumbura"),
    Africa_Cairo("东欧时间", 2, "Africa/Cairo"),
    Africa_Casablanca("西欧时间", 0, "Africa/Casablanca"),
    Africa_Ceuta("中欧时间", 1, "Africa/Ceuta"),
    Africa_Conakry("格林威治时间", 0, "Africa/Conakry"),
    Africa_Dakar("格林威治时间", 0, "Africa/Dakar"),
    Africa_Dar_es_Salaam("东非时间", 3, "Africa/Dar_es_Salaam"),
    Africa_Djibouti("东非时间", 3, "Africa/Djibouti"),
    Africa_Douala("西非时间", 1, "Africa/Douala"),
    Africa_El_Aaiun("西欧时间", 0, "Africa/El_Aaiun"),
    Africa_Freetown("格林威治时间", 0, "Africa/Freetown"),
    Africa_Gaborone("中非时间", 2, "Africa/Gaborone"),
    Africa_Harare("中非时间", 2, "Africa/Harare"),
    Africa_Johannesburg("南非标准时间", 2, "Africa/Johannesburg"),
    Africa_Juba("东非时间", 3, "Africa/Juba"),
    Africa_Kampala("东非时间", 3, "Africa/Kampala"),
    Africa_Khartoum("中非时间", 2, "Africa/Khartoum"),
    Africa_Kigali("中非时间", 2, "Africa/Kigali"),
    Africa_Kinshasa("西非时间", 1, "Africa/Kinshasa"),
    Africa_Lagos("西非时间", 1, "Africa/Lagos"),
    Africa_Libreville("西非时间", 1, "Africa/Libreville"),
    Africa_Lome("格林威治时间", 0, "Africa/Lome"),
    Africa_Luanda("西非时间", 1, "Africa/Luanda"),
    Africa_Lubumbashi("中非时间", 2, "Africa/Lubumbashi"),
    Africa_Lusaka("中非时间", 2, "Africa/Lusaka"),
    Africa_Malabo("西非时间", 1, "Africa/Malabo"),
    Africa_Maputo("中非时间", 2, "Africa/Maputo"),
    Africa_Maseru("南非标准时间", 2, "Africa/Maseru"),
    Africa_Mbabane("南非标准时间", 2, "Africa/Mbabane"),
    Africa_Mogadishu("东非时间", 3, "Africa/Mogadishu"),
    Africa_Monrovia("格林威治时间", 0, "Africa/Monrovia"),
    Africa_Nairobi("东非时间", 3, "Africa/Nairobi"),
    Africa_Ndjamena("西非时间", 1, "Africa/Ndjamena"),
    Africa_Niamey("西非时间", 1, "Africa/Niamey"),
    Africa_Nouakchott("格林威治时间", 0, "Africa/Nouakchott"),
    Africa_Ouagadougou("格林威治时间", 0, "Africa/Ouagadougou"),
    Africa_Porto_Novo("西非时间", 1, "Africa/Porto-Novo"),
    Africa_Sao_Tome("西非时间", 1, "Africa/Sao_Tome"),
    Africa_Timbuktu("格林威治时间", 0, "Africa/Timbuktu"),
    Africa_Tripoli("东欧时间", 2, "Africa/Tripoli"),
    Africa_Tunis("中欧时间", 1, "Africa/Tunis"),
    Africa_Windhoek("中非时间", 2, "Africa/Windhoek"),
    America_Adak("夏威夷标准时间", -10, "America/Adak"),
    America_Anchorage("阿拉斯加标准时间", -9, "America/Anchorage"),
    America_Anguilla("大西洋标准时间", -4, "America/Anguilla"),
    America_Antigua("大西洋标准时间", -4, "America/Antigua"),
    America_Araguaina("巴西利亚时间", -3, "America/Araguaina"),
    America_Argentina_Buenos_Aires("阿根廷时间", -3, "America/Argentina/Buenos_Aires"),
    America_Argentina_Catamarca("阿根廷时间", -3, "America/Argentina/Catamarca"),
    America_Argentina_ComodRivadavia("阿根廷时间", -3, "America/Argentina/ComodRivadavia"),
    America_Argentina_Cordoba("阿根廷时间", -3, "America/Argentina/Cordoba"),
    America_Argentina_Jujuy("阿根廷时间", -3, "America/Argentina/Jujuy"),
    America_Argentina_La_Rioja("阿根廷时间", -3, "America/Argentina/La_Rioja"),
    America_Argentina_Mendoza("阿根廷时间", -3, "America/Argentina/Mendoza"),
    America_Argentina_Rio_Gallegos("阿根廷时间", -3, "America/Argentina/Rio_Gallegos"),
    America_Argentina_Salta("阿根廷时间", -3, "America/Argentina/Salta"),
    America_Argentina_San_Juan("阿根廷时间", -3, "America/Argentina/San_Juan"),
    America_Argentina_San_Luis("阿根廷时间", -3, "America/Argentina/San_Luis"),
    America_Argentina_Tucuman("阿根廷时间", -3, "America/Argentina/Tucuman"),
    America_Argentina_Ushuaia("阿根廷时间", -3, "America/Argentina/Ushuaia"),
    America_Aruba("大西洋标准时间", -4, "America/Aruba"),
    America_Asuncion("巴拉圭时间", -4, "America/Asuncion"),
    America_Atikokan("东部标准时间", -5, "America/Atikokan"),
    America_Atka("夏威夷标准时间", -10, "America/Atka"),
    America_Bahia("巴西利亚时间", -3, "America/Bahia"),
    America_Bahia_Banderas("中央标准时间", -6, "America/Bahia_Banderas"),
    America_Barbados("大西洋标准时间", -4, "America/Barbados"),
    America_Belem("巴西利亚时间", -3, "America/Belem"),
    America_Belize("中央标准时间", -6, "America/Belize"),
    America_Blanc_Sablon("大西洋标准时间", -4, "America/Blanc-Sablon"),
    America_Boa_Vista("亚马逊时间", -4, "America/Boa_Vista"),
    America_Bogota("哥伦比亚时间", -5, "America/Bogota"),
    America_Boise("Mountain 标准时间", -7, "America/Boise"),
    America_Buenos_Aires("阿根廷时间", -3, "America/Buenos_Aires"),
    America_Cambridge_Bay("Mountain 标准时间", -7, "America/Cambridge_Bay"),
    America_Campo_Grande("亚马逊时间", -4, "America/Campo_Grande"),
    America_Cancun("东部标准时间", -5, "America/Cancun"),
    America_Caracas("委内瑞拉时间", -4, "America/Caracas"),
    America_Catamarca("阿根廷时间", -3, "America/Catamarca"),
    America_Cayenne("法属圭亚那时间", -3, "America/Cayenne"),
    America_Cayman("东部标准时间", -5, "America/Cayman"),
    America_Chicago("中央标准时间", -6, "America/Chicago"),
    America_Chihuahua("Mountain 标准时间", -7, "America/Chihuahua"),
    America_Coral_Harbour("东部标准时间", -5, "America/Coral_Harbour"),
    America_Cordoba("阿根廷时间", -3, "America/Cordoba"),
    America_Costa_Rica("中央标准时间", -6, "America/Costa_Rica"),
    America_Creston("Mountain 标准时间", -7, "America/Creston"),
    America_Cuiaba("亚马逊时间", -4, "America/Cuiaba"),
    America_Curacao("大西洋标准时间", -4, "America/Curacao"),
    America_Danmarkshavn("格林威治时间", 0, "America/Danmarkshavn"),
    America_Dawson("太平洋标准时间", -8, "America/Dawson"),
    America_Dawson_Creek("Mountain 标准时间", -7, "America/Dawson_Creek"),
    America_Denver("Mountain 标准时间", -7, "America/Denver"),
    America_Detroit("东部标准时间", -5, "America/Detroit"),
    America_Dominica("大西洋标准时间", -4, "America/Dominica"),
    America_Edmonton("Mountain 标准时间", -7, "America/Edmonton"),
    America_Eirunepe("Acre 时间", -5, "America/Eirunepe"),
    America_El_Salvador("中央标准时间", -6, "America/El_Salvador"),
    America_Ensenada("太平洋标准时间", -8, "America/Ensenada"),
    America_Fort_Nelson("Mountain 标准时间", -7, "America/Fort_Nelson"),
    America_Fort_Wayne("东部标准时间", -5, "America/Fort_Wayne"),
    America_Fortaleza("巴西利亚时间", -3, "America/Fortaleza"),
    America_Glace_Bay("大西洋标准时间", -4, "America/Glace_Bay"),
    America_Godthab("西格林兰岛时间", -3, "America/Godthab"),
    America_Goose_Bay("大西洋标准时间", -4, "America/Goose_Bay"),
    America_Grand_Turk("大西洋标准时间", -5, "America/Grand_Turk"),
    America_Grenada("大西洋标准时间", -4, "America/Grenada"),
    America_Guadeloupe("大西洋标准时间", -4, "America/Guadeloupe"),
    America_Guatemala("中央标准时间", -6, "America/Guatemala"),
    America_Guayaquil("厄瓜多尔时间", -5, "America/Guayaquil"),
    America_Guyana("圭亚那时间", -4, "America/Guyana"),
    America_Halifax("大西洋标准时间", -4, "America/Halifax"),
    America_Havana("古巴标准时间", -5, "America/Havana"),
    America_Hermosillo("Mountain 标准时间", -7, "America/Hermosillo"),
    America_Indiana_Indianapolis("东部标准时间", -5, "America/Indiana/Indianapolis"),
    America_Indiana_Knox("中央标准时间", -6, "America/Indiana/Knox"),
    America_Indiana_Marengo("东部标准时间", -5, "America/Indiana/Marengo"),
    America_Indiana_Petersburg("东部标准时间", -5, "America/Indiana/Petersburg"),
    America_Indiana_Tell_City("中央标准时间", -6, "America/Indiana/Tell_City"),
    America_Indiana_Vevay("东部标准时间", -5, "America/Indiana/Vevay"),
    America_Indiana_Vincennes("东部标准时间", -5, "America/Indiana/Vincennes"),
    America_Indiana_Winamac("东部标准时间", -5, "America/Indiana/Winamac"),
    America_Indianapolis("东部标准时间", -5, "America/Indianapolis"),
    America_Inuvik("Mountain 标准时间", -7, "America/Inuvik"),
    America_Iqaluit("东部标准时间", -5, "America/Iqaluit"),
    America_Jamaica("东部标准时间", -5, "America/Jamaica"),
    America_Jujuy("阿根廷时间", -3, "America/Jujuy"),
    America_Juneau("阿拉斯加标准时间", -9, "America/Juneau"),
    America_Kentucky_Louisville("东部标准时间", -5, "America/Kentucky/Louisville"),
    America_Kentucky_Monticello("东部标准时间", -5, "America/Kentucky/Monticello"),
    America_Knox_IN("中央标准时间", -6, "America/Knox_IN"),
    America_Kralendijk("大西洋标准时间", -4, "America/Kralendijk"),
    America_La_Paz("玻利维亚时间", -4, "America/La_Paz"),
    America_Lima("秘鲁时间", -5, "America/Lima"),
    America_Los_Angeles("太平洋标准时间", -8, "America/Los_Angeles"),
    America_Louisville("东部标准时间", -5, "America/Louisville"),
    America_Lower_Princes("大西洋标准时间", -4, "America/Lower_Princes"),
    America_Maceio("巴西利亚时间", -3, "America/Maceio"),
    America_Managua("中央标准时间", -6, "America/Managua"),
    America_Manaus("亚马逊时间", -4, "America/Manaus"),
    America_Marigot("大西洋标准时间", -4, "America/Marigot"),
    America_Martinique("大西洋标准时间", -4, "America/Martinique"),
    America_Matamoros("中央标准时间", -6, "America/Matamoros"),
    America_Mazatlan("Mountain 标准时间", -7, "America/Mazatlan"),
    America_Mendoza("阿根廷时间", -3, "America/Mendoza"),
    America_Menominee("中央标准时间", -6, "America/Menominee"),
    America_Merida("中央标准时间", -6, "America/Merida"),
    America_Metlakatla("阿拉斯加标准时间", -9, "America/Metlakatla"),
    America_Mexico_City("中央标准时间", -6, "America/Mexico_City"),
    America_Miquelon("皮埃尔岛及密克隆岛标准时间", -3, "America/Miquelon"),
    America_Moncton("大西洋标准时间", -4, "America/Moncton"),
    America_Monterrey("中央标准时间", -6, "America/Monterrey"),
    America_Montevideo("乌拉圭时间", -3, "America/Montevideo"),
    America_Montreal("东部标准时间", -5, "America/Montreal"),
    America_Montserrat("大西洋标准时间", -4, "America/Montserrat"),
    America_Nassau("东部标准时间", -5, "America/Nassau"),
    America_New_York("东部标准时间", -5, "America/New_York"),
    America_Nipigon("东部标准时间", -5, "America/Nipigon"),
    America_Nome("阿拉斯加标准时间", -9, "America/Nome"),
    America_Noronha("费尔南多德诺罗尼亚时间", -2, "America/Noronha"),
    America_North_Dakota_Beulah("中央标准时间", -6, "America/North_Dakota/Beulah"),
    America_North_Dakota_Center("中央标准时间", -6, "America/North_Dakota/Center"),
    America_North_Dakota_New_Salem("中央标准时间", -6, "America/North_Dakota/New_Salem"),
    America_Ojinaga("Mountain 标准时间", -7, "America/Ojinaga"),
    America_Panama("东部标准时间", -5, "America/Panama"),
    America_Pangnirtung("东部标准时间", -5, "America/Pangnirtung"),
    America_Paramaribo("苏利南时间", -3, "America/Paramaribo"),
    America_Phoenix("Mountain 标准时间", -7, "America/Phoenix"),
    America_Port_au_Prince("东部标准时间", -5, "America/Port-au-Prince"),
    America_Port_of_Spain("大西洋标准时间", -4, "America/Port_of_Spain"),
    America_Porto_Acre("Acre 时间", -5, "America/Porto_Acre"),
    America_Porto_Velho("亚马逊时间", -4, "America/Porto_Velho"),
    America_Puerto_Rico("大西洋标准时间", -4, "America/Puerto_Rico"),
    America_Punta_Arenas("GMT-03:00", -3, "America/Punta_Arenas"),
    America_Rainy_River("中央标准时间", -6, "America/Rainy_River"),
    America_Rankin_Inlet("中央标准时间", -6, "America/Rankin_Inlet"),
    America_Recife("巴西利亚时间", -3, "America/Recife"),
    America_Regina("中央标准时间", -6, "America/Regina"),
    America_Resolute("中央标准时间", -6, "America/Resolute"),
    America_Rio_Branco("Acre 时间", -5, "America/Rio_Branco"),
    America_Rosario("阿根廷时间", -3, "America/Rosario"),
    America_Santa_Isabel("太平洋标准时间", -8, "America/Santa_Isabel"),
    America_Santarem("巴西利亚时间", -3, "America/Santarem"),
    America_Santiago("智利时间", -4, "America/Santiago"),
    America_Santo_Domingo("大西洋标准时间", -4, "America/Santo_Domingo"),
    America_Sao_Paulo("巴西利亚时间", -3, "America/Sao_Paulo"),
    America_Scoresbysund("东格林岛时间", -1, "America/Scoresbysund"),
    America_Shiprock("Mountain 标准时间", -7, "America/Shiprock"),
    America_Sitka("阿拉斯加标准时间", -9, "America/Sitka"),
    America_St_Barthelemy("大西洋标准时间", -4, "America/St_Barthelemy"),
    America_St_Johns("纽芬兰标准时间", -3, "America/St_Johns"),
    America_St_Kitts("大西洋标准时间", -4, "America/St_Kitts"),
    America_St_Lucia("大西洋标准时间", -4, "America/St_Lucia"),
    America_St_Thomas("大西洋标准时间", -4, "America/St_Thomas"),
    America_St_Vincent("大西洋标准时间", -4, "America/St_Vincent"),
    America_Swift_Current("中央标准时间", -6, "America/Swift_Current"),
    America_Tegucigalpa("中央标准时间", -6, "America/Tegucigalpa"),
    America_Thule("大西洋标准时间", -4, "America/Thule"),
    America_Thunder_Bay("东部标准时间", -5, "America/Thunder_Bay"),
    America_Tijuana("太平洋标准时间", -8, "America/Tijuana"),
    America_Toronto("东部标准时间", -5, "America/Toronto"),
    America_Tortola("大西洋标准时间", -4, "America/Tortola"),
    America_Vancouver("太平洋标准时间", -8, "America/Vancouver"),
    America_Virgin("大西洋标准时间", -4, "America/Virgin"),
    America_Whitehorse("太平洋标准时间", -8, "America/Whitehorse"),
    America_Winnipeg("中央标准时间", -6, "America/Winnipeg"),
    America_Yakutat("阿拉斯加标准时间", -9, "America/Yakutat"),
    America_Yellowknife("Mountain 标准时间", -7, "America/Yellowknife"),
    Antarctica_Casey("西部标准时间 (澳大利亚)", 11, "Antarctica/Casey"),
    Antarctica_Davis("戴维斯时间", 7, "Antarctica/Davis"),
    Antarctica_Macquarie("麦夸里岛时间", 11, "Antarctica/Macquarie"),
    Antarctica_Mawson("莫森时间", 5, "Antarctica/Mawson"),
    Antarctica_McMurdo("新西兰标准时间", 12, "Antarctica/McMurdo"),
    Antarctica_Palmer("智利时间", -3, "Antarctica/Palmer"),
    Antarctica_Rothera("罗瑟拉时间", -3, "Antarctica/Rothera"),
    Antarctica_South_Pole("新西兰标准时间", 12, "Antarctica/South_Pole"),
    Antarctica_Syowa("Syowa 时间", 3, "Antarctica/Syowa"),
    Antarctica_Troll("协调世界时间", 0, "Antarctica/Troll"),
    Antarctica_Vostok("莫斯托克时间", 6, "Antarctica/Vostok"),
    Arctic_Longyearbyen("中欧时间", 1, "Arctic/Longyearbyen"),
    Asia_Aden("阿拉伯标准时间", 3, "Asia/Aden"),
    Asia_Almaty("Alma-Ata 时间", 6, "Asia/Almaty"),
    Asia_Amman("东欧时间", 2, "Asia/Amman"),
    Asia_Anadyr("阿那底河时间", 12, "Asia/Anadyr"),
    Asia_Aqtau("Aqtau 时间", 5, "Asia/Aqtau"),
    Asia_Aqtobe("Aqtobe 时间", 5, "Asia/Aqtobe"),
    Asia_Ashgabat("土库曼时间", 5, "Asia/Ashgabat"),
    Asia_Ashkhabad("土库曼时间", 5, "Asia/Ashkhabad"),
    Asia_Atyrau("GMT+05:00", 5, "Asia/Atyrau"),
    Asia_Baghdad("阿拉伯标准时间", 3, "Asia/Baghdad"),
    Asia_Bahrain("阿拉伯标准时间", 3, "Asia/Bahrain"),
    Asia_Baku("亚塞拜然时间", 4, "Asia/Baku"),
    Asia_Bangkok("印度支那时间", 7, "Asia/Bangkok"),
    Asia_Barnaul("GMT+07:00", 7, "Asia/Barnaul"),
    Asia_Beirut("东欧时间", 2, "Asia/Beirut"),
    Asia_Bishkek("吉尔吉斯斯坦时间", 6, "Asia/Bishkek"),
    Asia_Brunei("文莱时间", 8, "Asia/Brunei"),
    Asia_Calcutta("印度标准时间", 5, "Asia/Calcutta"),
    Asia_Chita("亚库次克时间", 9, "Asia/Chita"),
    Asia_Choibalsan("Choibalsan 时间", 8, "Asia/Choibalsan"),
    Asia_Chongqing("中国标准时间", 8, "Asia/Chongqing"),
    Asia_Chungking("中国标准时间", 8, "Asia/Chungking"),
    Asia_Colombo("印度标准时间", 5, "Asia/Colombo"),
    Asia_Dacca("孟加拉时间", 6, "Asia/Dacca"),
    Asia_Damascus("东欧时间", 2, "Asia/Damascus"),
    Asia_Dhaka("孟加拉时间", 6, "Asia/Dhaka"),
    Asia_Dili("东帝汶时间", 9, "Asia/Dili"),
    Asia_Dubai("波斯湾标准时间", 4, "Asia/Dubai"),
    Asia_Dushanbe("塔吉克斯坦时间", 5, "Asia/Dushanbe"),
    Asia_Famagusta("GMT+02:00", 2, "Asia/Famagusta"),
    Asia_Gaza("东欧时间", 2, "Asia/Gaza"),
    Asia_Harbin("中国标准时间", 8, "Asia/Harbin"),
    Asia_Hebron("东欧时间", 2, "Asia/Hebron"),
    Asia_Ho_Chi_Minh("印度支那时间", 7, "Asia/Ho_Chi_Minh"),
    Asia_Hong_Kong("香港时间", 8, "Asia/Hong_Kong"),
    Asia_Hovd("科布多时间", 7, "Asia/Hovd"),
    Asia_Irkutsk("伊尔库次克时间", 8, "Asia/Irkutsk"),
    Asia_Istanbul("东欧时间", 3, "Asia/Istanbul"),
    Asia_Jakarta("西印度尼西亚时间", 7, "Asia/Jakarta"),
    Asia_Jayapura("东印度尼西亚时间", 9, "Asia/Jayapura"),
    Asia_Jerusalem("以色列标准时间", 2, "Asia/Jerusalem"),
    Asia_Kabul("阿富汗时间", 4, "Asia/Kabul"),
    Asia_Kamchatka("彼得罗巴甫洛夫斯克时间", 12, "Asia/Kamchatka"),
    Asia_Karachi("巴基斯坦时间", 5, "Asia/Karachi"),
    Asia_Kashgar("中国标准时间", 6, "Asia/Kashgar"),
    Asia_Kathmandu("尼泊尔时间", 5, "Asia/Kathmandu"),
    Asia_Katmandu("尼泊尔时间", 5, "Asia/Katmandu"),
    Asia_Khandyga("亚库次克时间", 9, "Asia/Khandyga"),
    Asia_Kolkata("印度标准时间", 5, "Asia/Kolkata"),
    Asia_Krasnoyarsk("克拉斯诺亚尔斯克时间", 7, "Asia/Krasnoyarsk"),
    Asia_Kuala_Lumpur("马来西亚时间", 8, "Asia/Kuala_Lumpur"),
    Asia_Kuching("马来西亚时间", 8, "Asia/Kuching"),
    Asia_Kuwait("阿拉伯标准时间", 3, "Asia/Kuwait"),
    Asia_Macao("中国标准时间", 8, "Asia/Macao"),
    Asia_Macau("中国标准时间", 8, "Asia/Macau"),
    Asia_Magadan("Magadan 时间", 11, "Asia/Magadan"),
    Asia_Makassar("中部印度尼西亚时间", 8, "Asia/Makassar"),
    Asia_Manila("菲律宾时间", 8, "Asia/Manila"),
    Asia_Muscat("波斯湾标准时间", 4, "Asia/Muscat"),
    Asia_Nicosia("东欧时间", 2, "Asia/Nicosia"),
    Asia_Novokuznetsk("克拉斯诺亚尔斯克时间", 7, "Asia/Novokuznetsk"),
    Asia_Novosibirsk("Novosibirsk 时间", 7, "Asia/Novosibirsk"),
    Asia_Omsk("鄂木斯克时间", 6, "Asia/Omsk"),
    Asia_Oral("Oral 时间", 5, "Asia/Oral"),
    Asia_Phnom_Penh("印度支那时间", 7, "Asia/Phnom_Penh"),
    Asia_Pontianak("西印度尼西亚时间", 7, "Asia/Pontianak"),
    Asia_Pyongyang("韩国标准时间", 8, "Asia/Pyongyang"),
    Asia_Qatar("阿拉伯标准时间", 3, "Asia/Qatar"),
    Asia_Qyzylorda("Qyzylorda 时间", 6, "Asia/Qyzylorda"),
    Asia_Rangoon("缅甸时间", 6, "Asia/Rangoon"),
    Asia_Riyadh("阿拉伯标准时间", 3, "Asia/Riyadh"),
    Asia_Saigon("印度支那时间", 7, "Asia/Saigon"),
    Asia_Sakhalin("库页岛时间", 11, "Asia/Sakhalin"),
    Asia_Samarkand("乌兹别克斯坦时间", 5, "Asia/Samarkand"),
    Asia_Seoul("韩国标准时间", 9, "Asia/Seoul"),
    Asia_Shanghai("中国标准时间", 8, "Asia/Shanghai"),
    Asia_Singapore("新加坡时间", 8, "Asia/Singapore"),
    Asia_Srednekolymsk("Srednekolymsk Time", 11, "Asia/Srednekolymsk"),
    Asia_Taipei("中国标准时间", 8, "Asia/Taipei"),
    Asia_Tashkent("乌兹别克斯坦时间", 5, "Asia/Tashkent"),
    Asia_Tbilisi("乔治亚时间", 4, "Asia/Tbilisi"),
    Asia_Tehran("伊朗标准时间", 3, "Asia/Tehran"),
    Asia_Tel_Aviv("以色列标准时间", 2, "Asia/Tel_Aviv"),
    Asia_Thimbu("不丹时间", 6, "Asia/Thimbu"),
    Asia_Thimphu("不丹时间", 6, "Asia/Thimphu"),
    Asia_Tokyo("日本标准时间", 9, "Asia/Tokyo"),
    Asia_Tomsk("GMT+07:00", 7, "Asia/Tomsk"),
    Asia_Ujung_Pandang("中部印度尼西亚时间", 8, "Asia/Ujung_Pandang"),
    Asia_Ulaanbaatar("库伦时间", 8, "Asia/Ulaanbaatar"),
    Asia_Ulan_Bator("库伦时间", 8, "Asia/Ulan_Bator"),
    Asia_Urumqi("中国标准时间", 6, "Asia/Urumqi"),
    Asia_Ust_Nera("乌斯季涅拉时间", 10, "Asia/Ust-Nera"),
    Asia_Vientiane("印度支那时间", 7, "Asia/Vientiane"),
    Asia_Vladivostok("海参崴时间", 10, "Asia/Vladivostok"),
    Asia_Yakutsk("亚库次克时间", 9, "Asia/Yakutsk"),
    Asia_Yangon("缅甸时间", 6, "Asia/Yangon"),
    Asia_Yekaterinburg("Yekaterinburg 时间", 5, "Asia/Yekaterinburg"),
    Asia_Yerevan("亚美尼亚时间", 4, "Asia/Yerevan"),
    Atlantic_Azores("亚速尔群岛时间", -1, "Atlantic/Azores"),
    Atlantic_Bermuda("大西洋标准时间", -4, "Atlantic/Bermuda"),
    Atlantic_Canary("西欧时间", 0, "Atlantic/Canary"),
    Atlantic_Cape_Verde("佛德角时间", -1, "Atlantic/Cape_Verde"),
    Atlantic_Faeroe("西欧时间", 0, "Atlantic/Faeroe"),
    Atlantic_Faroe("西欧时间", 0, "Atlantic/Faroe"),
    Atlantic_Jan_Mayen("中欧时间", 1, "Atlantic/Jan_Mayen"),
    Atlantic_Madeira("西欧时间", 0, "Atlantic/Madeira"),
    Atlantic_Reykjavik("格林威治时间", 0, "Atlantic/Reykjavik"),
    Atlantic_South_Georgia("南乔治亚标准时间", -2, "Atlantic/South_Georgia"),
    Atlantic_St_Helena("格林威治时间", 0, "Atlantic/St_Helena"),
    Atlantic_Stanley("福克兰群岛时间", -3, "Atlantic/Stanley"),
    Australia_ACT("东部标准时间 (新南威尔斯)", 10, "Australia/ACT"),
    Australia_Adelaide("中央标准时间 (南澳大利亚)", 9, "Australia/Adelaide"),
    Australia_Brisbane("东部标准时间 (昆士兰)", 10, "Australia/Brisbane"),
    Australia_Broken_Hill("中央标准时间 (南澳大利亚/新南威尔斯)", 9, "Australia/Broken_Hill"),
    Australia_Canberra("东部标准时间 (新南威尔斯)", 10, "Australia/Canberra"),
    Australia_Currie("东部标准时间 (新南威尔斯)", 10, "Australia/Currie"),
    Australia_Darwin("中央标准时间 (北领地)", 9, "Australia/Darwin"),
    Australia_Eucla("中西部标准时间 (澳大利亚)", 8, "Australia/Eucla"),
    Australia_Hobart("东部标准时间 (塔斯马尼亚)", 10, "Australia/Hobart"),
    Australia_LHI("豪公标准时间", 10, "Australia/LHI"),
    Australia_Lindeman("东部标准时间 (昆士兰)", 10, "Australia/Lindeman"),
    Australia_Lord_Howe("豪公标准时间", 10, "Australia/Lord_Howe"),
    Australia_Melbourne("东部标准时间 (维多利亚)", 10, "Australia/Melbourne"),
    Australia_NSW("东部标准时间 (新南威尔斯)", 10, "Australia/NSW"),
    Australia_North("中央标准时间 (北领地)", 9, "Australia/North"),
    Australia_Perth("西部标准时间 (澳大利亚)", 8, "Australia/Perth"),
    Australia_Queensland("东部标准时间 (昆士兰)", 10, "Australia/Queensland"),
    Australia_South("中央标准时间 (南澳大利亚)", 9, "Australia/South"),
    Australia_Sydney("东部标准时间 (新南威尔斯)", 10, "Australia/Sydney"),
    Australia_Tasmania("东部标准时间 (塔斯马尼亚)", 10, "Australia/Tasmania"),
    Australia_Victoria("东部标准时间 (维多利亚)", 10, "Australia/Victoria"),
    Australia_West("西部标准时间 (澳大利亚)", 8, "Australia/West"),
    Australia_Yancowinna("中央标准时间 (南澳大利亚/新南威尔斯)", 9, "Australia/Yancowinna"),
    Brazil_Acre("Acre 时间", -5, "Brazil/Acre"),
    Brazil_DeNoronha("费尔南多德诺罗尼亚时间", -2, "Brazil/DeNoronha"),
    Brazil_East("巴西利亚时间", -3, "Brazil/East"),
    Brazil_West("亚马逊时间", -4, "Brazil/West"),
    CET("中欧时间", 1, "CET"),
    CST6CDT("中央标准时间", -6, "CST6CDT"),
    Canada_Atlantic("大西洋标准时间", -4, "Canada/Atlantic"),
    Canada_Central("中央标准时间", -6, "Canada/Central"),
    Canada_Eastern("东部标准时间", -5, "Canada/Eastern"),
    Canada_Mountain("Mountain 标准时间", -7, "Canada/Mountain"),
    Canada_Newfoundland("纽芬兰标准时间", -3, "Canada/Newfoundland"),
    Canada_Pacific("太平洋标准时间", -8, "Canada/Pacific"),
    Canada_Saskatchewan("中央标准时间", -6, "Canada/Saskatchewan"),
    Canada_Yukon("太平洋标准时间", -8, "Canada/Yukon"),
    Chile_Continental("智利时间", -4, "Chile/Continental"),
    Chile_EasterIsland("复活岛时间", -6, "Chile/EasterIsland"),
    Cuba("古巴标准时间", -5, "Cuba"),
    EET("东欧时间", 2, "EET"),
    EST5EDT("东部标准时间", -5, "EST5EDT"),
    Egypt("东欧时间", 2, "Egypt"),
    Eire("格林威治时间", 0, "Eire"),
    Etc_GMT("格林威治时间", 0, "Etc/GMT"),
    Etc_GMT_ADD_0("格林威治时间",0,"Etc/GMT+0"),
    Etc_GMT_ADD_1("GMT-01:00",-1,"Etc/GMT+1"),
    Etc_GMT_ADD_10("GMT-10:00",-10,"Etc/GMT+10"),
    Etc_GMT_ADD_11("GMT-11:00",-11,"Etc/GMT+11"),
    Etc_GMT_ADD_12("GMT-12:00",-12,"Etc/GMT+12"),
    Etc_GMT_ADD_2("GMT-02:00",-2,"Etc/GMT+2"),
    Etc_GMT_ADD_3("GMT-03:00",-3,"Etc/GMT+3"),
    Etc_GMT_ADD_4("GMT-04:00",-4,"Etc/GMT+4"),
    Etc_GMT_ADD_5("GMT-05:00",-5,"Etc/GMT+5"),
    Etc_GMT_ADD_6("GMT-06:00",-6,"Etc/GMT+6"),
    Etc_GMT_ADD_7("GMT-07:00",-7,"Etc/GMT+7"),
    Etc_GMT_ADD_8("GMT-08:00",-8,"Etc/GMT+8"),
    Etc_GMT_ADD_9("GMT-09:00",-9,"Etc/GMT+9"),
    Etc_GMT_Subtract_0("格林威治时间",0,"Etc/GMT-0"),
    Etc_GMT_Subtract_1("GMT+01:00",1,"Etc/GMT-1"),
    Etc_GMT_Subtract_10("GMT+10:00",10,"Etc/GMT-10"),
    Etc_GMT_Subtract_11("GMT+11:00",11,"Etc/GMT-11"),
    Etc_GMT_Subtract_12("GMT+12:00",12,"Etc/GMT-12"),
    Etc_GMT_Subtract_13("GMT+13:00",13,"Etc/GMT-13"),
    Etc_GMT_Subtract_14("GMT+14:00",14,"Etc/GMT-14"),
    Etc_GMT_Subtract_2("GMT+02:00",2,"Etc/GMT-2"),
    Etc_GMT_Subtract_3("GMT+03:00",3,"Etc/GMT-3"),
    Etc_GMT_Subtract_4("GMT+04:00",4,"Etc/GMT-4"),
    Etc_GMT_Subtract_5("GMT+05:00",5,"Etc/GMT-5"),
    Etc_GMT_Subtract_6("GMT+06:00",6,"Etc/GMT-6"),
    Etc_GMT_Subtract_7("GMT+07:00",7,"Etc/GMT-7"),
    Etc_GMT_Subtract_8("GMT+08:00",8,"Etc/GMT-8"),
    Etc_GMT_Subtract_9("GMT+09:00",9,"Etc/GMT-9"),
    Etc_GMT0("格林威治时间",0,"Etc/GMT0"),
    Etc_Greenwich("格林威治时间",0,"Etc/Greenwich"),
    Etc_UCT("协调世界时间",0,"Etc/UCT"),
    Etc_UTC("协调世界时间",0,"Etc/UTC"),
    Etc_Universal("协调世界时间",0,"Etc/Universal"),
    Etc_Zulu("协调世界时间",0,"Etc/Zulu"),
    Europe_Amsterdam("中欧时间",1,"Europe/Amsterdam"),
    Europe_Andorra("中欧时间",1,"Europe/Andorra"),
    Europe_Astrakhan("GMT+04:00",4,"Europe/Astrakhan"),
    Europe_Athens("东欧时间",2,"Europe/Athens"),
    Europe_Belfast("格林威治时间",0,"Europe/Belfast"),
    Europe_Belgrade("中欧时间",1,"Europe/Belgrade"),
    Europe_Berlin("中欧时间",1,"Europe/Berlin"),
    Europe_Bratislava("中欧时间",1,"Europe/Bratislava"),
    Europe_Brussels("中欧时间",1,"Europe/Brussels"),
    Europe_Bucharest("东欧时间",2,"Europe/Bucharest"),
    Europe_Budapest("中欧时间",1,"Europe/Budapest"),
    Europe_Busingen("中欧时间",1,"Europe/Busingen"),
    Europe_Chisinau("东欧时间",2,"Europe/Chisinau"),
    Europe_Copenhagen("中欧时间",1,"Europe/Copenhagen"),
    Europe_Dublin("格林威治时间",0,"Europe/Dublin"),
    Europe_Gibraltar("中欧时间",1,"Europe/Gibraltar"),
    Europe_Guernsey("格林威治时间",0,"Europe/Guernsey"),
    Europe_Helsinki("东欧时间",2,"Europe/Helsinki"),
    Europe_Isle_of_Man("格林威治时间",0,"Europe/Isle_of_Man"),
    Europe_Istanbul("东欧时间",3,"Europe/Istanbul"),
    Europe_Jersey("格林威治时间",0,"Europe/Jersey"),
    Europe_Kaliningrad("东欧时间",2,"Europe/Kaliningrad"),
    Europe_Kiev("东欧时间",2,"Europe/Kiev"),
    Europe_Kirov("GMT+03:00",3,"Europe/Kirov"),
    Europe_Lisbon("西欧时间",0,"Europe/Lisbon"),
    Europe_Ljubljana("中欧时间",1,"Europe/Ljubljana"),
    Europe_London("格林威治时间",0,"Europe/London"),
    Europe_Luxembourg("中欧时间",1,"Europe/Luxembourg"),
    Europe_Madrid("中欧时间",1,"Europe/Madrid"),
    Europe_Malta("中欧时间",1,"Europe/Malta"),
    Europe_Mariehamn("东欧时间",2,"Europe/Mariehamn"),
    Europe_Minsk("莫斯科标准时间",3,"Europe/Minsk"),
    Europe_Monaco("中欧时间",1,"Europe/Monaco"),
    Europe_Moscow("莫斯科标准时间",3,"Europe/Moscow"),
    Europe_Nicosia("东欧时间",2,"Europe/Nicosia"),
    Europe_Oslo("中欧时间",1,"Europe/Oslo"),
    Europe_Paris("中欧时间",1,"Europe/Paris"),
    Europe_Podgorica("中欧时间",1,"Europe/Podgorica"),
    Europe_Prague("中欧时间",1,"Europe/Prague"),
    Europe_Riga("东欧时间",2,"Europe/Riga"),
    Europe_Rome("中欧时间",1,"Europe/Rome"),
    Europe_Samara("沙马拉时间",4,"Europe/Samara"),
    Europe_San_Marino("中欧时间",1,"Europe/San_Marino"),
    Europe_Sarajevo("中欧时间",1,"Europe/Sarajevo"),
    Europe_Saratov("GMT+04:00",4,"Europe/Saratov"),
    Europe_Simferopol("莫斯科标准时间",3,"Europe/Simferopol"),
    Europe_Skopje("中欧时间",1,"Europe/Skopje"),
    Europe_Sofia("东欧时间",2,"Europe/Sofia"),
    Europe_Stockholm("中欧时间",1,"Europe/Stockholm"),
    Europe_Tallinn("东欧时间",2,"Europe/Tallinn"),
    Europe_Tirane("中欧时间",1,"Europe/Tirane"),
    Europe_Tiraspol("东欧时间",2,"Europe/Tiraspol"),
    Europe_Ulyanovsk("GMT+04:00",4,"Europe/Ulyanovsk"),
    Europe_Uzhgorod("东欧时间",2,"Europe/Uzhgorod"),
    Europe_Vaduz("中欧时间",1,"Europe/Vaduz"),
    Europe_Vatican("中欧时间",1,"Europe/Vatican"),
    Europe_Vienna("中欧时间",1,"Europe/Vienna"),
    Europe_Vilnius("东欧时间",2,"Europe/Vilnius"),
    Europe_Volgograd("莫斯科标准时间",3,"Europe/Volgograd"),
    Europe_Warsaw("中欧时间",1,"Europe/Warsaw"),
    Europe_Zagreb("中欧时间",1,"Europe/Zagreb"),
    Europe_Zaporozhye("东欧时间",2,"Europe/Zaporozhye"),
    Europe_Zurich("中欧时间",1,"Europe/Zurich"),
    GB("格林威治时间",0,"GB"),
    GB_Eire("格林威治时间",0,"GB-Eire"),
    GMT("格林威治时间",0,"GMT"),
    GMT0("格林威治时间",0,"GMT0"),
    Greenwich("格林威治时间",0,"Greenwich"),
    Hongkong("香港时间",8,"Hongkong"),
    Iceland("格林威治时间",0,"Iceland"),
    Indian_Antananarivo("东非时间",3,"Indian/Antananarivo"),
    Indian_Chagos("印度洋地带时间",6,"Indian/Chagos"),
    Indian_Christmas("圣诞岛时间",7,"Indian/Christmas"),
    Indian_Cocos("可可斯群岛时间",6,"Indian/Cocos"),
    Indian_Comoro("东非时间",3,"Indian/Comoro"),
    Indian_Kerguelen("法属南极时间",5,"Indian/Kerguelen"),
    Indian_Mahe("塞席尔群岛时间",4,"Indian/Mahe"),
    Indian_Maldives("马尔代夫时间",5,"Indian/Maldives"),
    Indian_Mauritius("摩里西斯时间",4,"Indian/Mauritius"),
    Indian_Mayotte("东非时间",3,"Indian/Mayotte"),
    Indian_Reunion("留尼旺岛时间",4,"Indian/Reunion"),
    Iran("伊朗标准时间",3,"Iran"),
    Israel("以色列标准时间",2,"Israel"),
    Jamaica("东部标准时间",-5,"Jamaica"),
    Japan("日本标准时间",9,"Japan"),
    Kwajalein("马绍尔群岛时间",12,"Kwajalein"),
    Libya("东欧时间",2,"Libya"),
    MET("中欧时间",1,"MET"),
    MST7MDT("Mountain 标准时间",-7,"MST7MDT"),
    Mexico_BajaNorte("太平洋标准时间",-8,"Mexico/BajaNorte"),
    Mexico_BajaSur("Mountain 标准时间",-7,"Mexico/BajaSur"),
    Mexico_General("中央标准时间",-6,"Mexico/General"),
    NZ("新西兰标准时间",12,"NZ"),
    NZ_CHAT("查萨姆标准时间",12,"NZ-CHAT"),
    Navajo("Mountain 标准时间",-7,"Navajo"),
    PRC("中国标准时间",8,"PRC"),
    PST8PDT("太平洋标准时间",-8,"PST8PDT"),
    Pacific_Apia("西萨摩亚时间",13,"Pacific/Apia"),
    Pacific_Auckland("新西兰标准时间",12,"Pacific/Auckland"),
    Pacific_Bougainville("Bougainville Standard Time",11,"Pacific/Bougainville"),
    Pacific_Chatham("查萨姆标准时间",12,"Pacific/Chatham"),
    Pacific_Chuuk("丘克时间",10,"Pacific/Chuuk"),
    Pacific_Easter("复活岛时间",-6,"Pacific/Easter"),
    Pacific_Efate("瓦奴阿图时间",11,"Pacific/Efate"),
    Pacific_Enderbury("菲尼克斯群岛时间",13,"Pacific/Enderbury"),
    Pacific_Fakaofo("托克劳群岛时间",13,"Pacific/Fakaofo"),
    Pacific_Fiji("斐济时间",12,"Pacific/Fiji"),
    Pacific_Funafuti("吐鲁瓦时间",12,"Pacific/Funafuti"),
    Pacific_Galapagos("加拉巴哥时间",-6,"Pacific/Galapagos"),
    Pacific_Gambier("冈比亚时间",-9,"Pacific/Gambier"),
    Pacific_Guadalcanal("所罗门群岛时间",11,"Pacific/Guadalcanal"),
    Pacific_Guam("Chamorro 标准时间",10,"Pacific/Guam"),
    Pacific_Honolulu("夏威夷标准时间",-10,"Pacific/Honolulu"),
    Pacific_Johnston("夏威夷标准时间",-10,"Pacific/Johnston"),
    Pacific_Kiritimati("Line 岛时间",14,"Pacific/Kiritimati"),
    Pacific_Kosrae("Kosrae 时间",11,"Pacific/Kosrae"),
    Pacific_Kwajalein("马绍尔群岛时间",12,"Pacific/Kwajalein"),
    Pacific_Majuro("马绍尔群岛时间",12,"Pacific/Majuro"),
    Pacific_Marquesas("马克萨斯时间",-9,"Pacific/Marquesas"),
    Pacific_Midway("萨摩亚群岛标准时间",-11,"Pacific/Midway"),
    Pacific_Nauru("诺鲁时间",12,"Pacific/Nauru"),
    Pacific_Niue("纽威岛时间",-11,"Pacific/Niue"),
    Pacific_Norfolk("诺福克时间",11,"Pacific/Norfolk"),
    Pacific_Noumea("新加勒多尼亚时间",11,"Pacific/Noumea"),
    Pacific_Pago_Pago("萨摩亚群岛标准时间",-11,"Pacific/Pago_Pago"),
    Pacific_Palau("帛琉时间",9,"Pacific/Palau"),
    Pacific_Pitcairn("皮特康岛标准时间",-8,"Pacific/Pitcairn"),
    Pacific_Pohnpei("波纳佩时间",11,"Pacific/Pohnpei"),
    Pacific_Ponape("波纳佩时间",11,"Pacific/Ponape"),
    Pacific_Port_Moresby("巴布亚新几内亚时间",10,"Pacific/Port_Moresby"),
    Pacific_Rarotonga("库克群岛时间",-10,"Pacific/Rarotonga"),
    Pacific_Saipan("Chamorro 标准时间",10,"Pacific/Saipan"),
    Pacific_Samoa("萨摩亚群岛标准时间",-11,"Pacific/Samoa"),
    Pacific_Tahiti("大溪地岛时间",-10,"Pacific/Tahiti"),
    Pacific_Tarawa("吉伯特群岛时间",12,"Pacific/Tarawa"),
    Pacific_Tongatapu("东加时间",13,"Pacific/Tongatapu"),
    Pacific_Truk("丘克时间",10,"Pacific/Truk"),
    Pacific_Wake("威克时间",12,"Pacific/Wake"),
    Pacific_Wallis("瓦利斯及福杜纳群岛时间",12,"Pacific/Wallis"),
    Pacific_Yap("丘克时间",10,"Pacific/Yap"),
    Poland("中欧时间",1,"Poland"),
    Portugal("西欧时间",0,"Portugal"),
    ROK("韩国标准时间",9,"ROK"),
    Singapore("新加坡时间",8,"Singapore"),
    SystemV_AST4("大西洋标准时间",-4,"SystemV/AST4"),
    SystemV_AST4ADT("大西洋标准时间",-4,"SystemV/AST4ADT"),
    SystemV_CST6("中央标准时间",-6,"SystemV/CST6"),
    SystemV_CST6CDT("中央标准时间",-6,"SystemV/CST6CDT"),
    SystemV_EST5("东部标准时间",-5,"SystemV/EST5"),
    SystemV_EST5EDT("东部标准时间",-5,"SystemV/EST5EDT"),
    SystemV_HST10("夏威夷标准时间",-10,"SystemV/HST10"),
    SystemV_MST7("Mountain 标准时间",-7,"SystemV/MST7"),
    SystemV_MST7MDT("Mountain 标准时间",-7,"SystemV/MST7MDT"),
    SystemV_PST8("太平洋标准时间",-8,"SystemV/PST8"),
    SystemV_PST8PDT("太平洋标准时间",-8,"SystemV/PST8PDT"),
    SystemV_YST9("阿拉斯加标准时间",-9,"SystemV/YST9"),
    SystemV_YST9YDT("阿拉斯加标准时间",-9,"SystemV/YST9YDT"),
    Turkey("东欧时间",3,"Turkey"),
    UCT("协调世界时间",0,"UCT"),
    US_Alaska("阿拉斯加标准时间",-9,"US/Alaska"),
    US_Aleutian("夏威夷标准时间",-10,"US/Aleutian"),
    US_Arizona("Mountain 标准时间",-7,"US/Arizona"),
    US_Central("中央标准时间",-6,"US/Central"),
    US_East_Indiana("东部标准时间",-5,"US/East-Indiana"),
    US_Eastern("东部标准时间",-5,"US/Eastern"),
    US_Hawaii("夏威夷标准时间",-10,"US/Hawaii"),
    US_Indiana_Starke("中央标准时间",-6,"US/Indiana-Starke"),
    US_Michigan("东部标准时间",-5,"US/Michigan"),
    US_Mountain("Mountain 标准时间",-7,"US/Mountain"),
    US_Pacific("太平洋标准时间",-8,"US/Pacific"),
    US_Pacific_New("太平洋标准时间",-8,"US/Pacific-New"),
    US_Samoa("萨摩亚群岛标准时间",-11,"US/Samoa"),
    UTC("协调世界时间",0,"UTC"),
    Universal("协调世界时间",0,"Universal"),
    W_SU("莫斯科标准时间",3,"W-SU"),
    WET("西欧时间",0,"WET"),
    Zulu("协调世界时间",0,"Zulu"),
    EST("东部标准时间",-5,"EST"),
    HST("夏威夷标准时间",-10,"HST"),
    MST("Mountain 标准时间",-7,"MST"),
    ACT("中央标准时间 (北领地)",9,"ACT"),
    AET("东部标准时间 (新南威尔斯)",10,"AET"),
    AGT("阿根廷时间",-3,"AGT"),
    ART("东欧时间",2,"ART"),
    AST("阿拉斯加标准时间",-9,"AST"),
    BET("巴西利亚时间",-3,"BET"),
    BST("孟加拉时间",6,"BST"),
    CAT("中非时间",2,"CAT"),
    CNT("纽芬兰标准时间",-3,"CNT"),
    CST("中央标准时间",-6,"CST"),
    CTT("中国标准时间",8,"CTT"),
    EAT("东非时间",3,"EAT"),
    ECT("中欧时间",1,"ECT"),
    IET("东部标准时间",-5,"IET"),
    IST("印度标准时间",5,"IST"),
    JST("日本标准时间",9,"JST"),
    MIT("西萨摩亚时间",13,"MIT"),
    NET("亚美尼亚时间",4,"NET"),
    NST("新西兰标准时间",12,"NST"),
    PLT("巴基斯坦时间",5,"PLT"),
    PNT("Mountain 标准时间",-7,"PNT"),
    PRT("大西洋标准时间",-4,"PRT"),
    PST("太平洋标准时间",-8,"PST"),
    SST("所罗门群岛时间",11,"SST"),
    VST("印度支那时间",7,"VST");

    private String CITY;
    private Integer TIMEZONE;
    private String TIMEZONEID;
    private CustomTimeZone(String CITY, Integer TIMEZONE, String TIMEZONEID) {
        this.CITY = CITY;
        this.TIMEZONE = TIMEZONE;
        this.TIMEZONEID = TIMEZONEID;
    }
    public String customToString() {
        return this.TIMEZONEID;
    }
    public Integer customToInt() {
        return this.TIMEZONE;
    }
    public String customToName() {
        return this.CITY;
    }
}